Repository PrestaShop/psgdpr, pull requests merged in 2020-04, with the labels that each got.

#75 Add ajax die
  controllers/front/FrontAjaxGdpr.php
Labels: QA ✔️

#78 Prevent deleting data when non-existing customer
  psgdpr.php
Labels: QA ✔️, bug

#74 Order confirmation form
  psgdpr.php
Labels: QA ✔️

#64 GDPR isn't working if the module have multiple form on same page
  views/templates/hook/displayGDPRConsent.tpl
Labels: QA ✔️, bug

#66 Fix duplicate html element id
  views/templates/front/customerAccount.tpl
Labels: QA ✔️, bug

#73 Fix Trying to get property of non-object
  psgdpr.php
Labels: QA ✔️, bug

#83 Remove ModuleAdminControllers from SEO & URLs page
  psgdpr.php
  upgrade/upgrade-1.1.4.php
Labels: Waiting for review, bug
